# UAPI Header export list
header-y += audio_effects.h
header-y += asequencer.h
header-y += asound.h
header-y += asound_fm.h
header-y += compress_offload.h
header-y += compress_params.h
header-y += emu10k1.h
header-y += hdsp.h
header-y += hdspm.h
header-y += voice_params.h
header-y += sb16_csp.h
header-y += sfnt_info.h

header-y += msm-dai-q6-v2.h
header-y += msm-dai-q6.h
header-y += msmcal-hwdep.h
